import { StyleSheet } from 'react-native';
import { colours, withAlpha } from './colourScheme';

export const styles = StyleSheet.create({
    topMargin: { marginTop: 50 },
    mb4: { marginBottom: 16 },
    row: { flexDirection: "row", justifyContent: "center", alignItems: "center", marginVertical: 8, },
    //text styles
    rowCenter: { alignItems: 'center', justifyContent: 'center' },
    title: { fontSize: 32, fontWeight: 'bold', marginBottom: 24, textAlign: 'center', fontFamily: 'InclusiveSans_700Bold' },
    subtitle: { fontSize: 24, marginBottom: 16, textAlign: 'center', fontFamily: 'InclusiveSans_400Regular' },
    heading: { fontWeight: 'bold', fontFamily: 'InclusiveSans_700Bold', },
    sectionTitle: { fontWeight: 'bold', marginBottom: 8, fontFamily: 'InclusiveSans_700Bold', },
    bold: { fontWeight: 'bold' },
    darkText: { color: colours.darkGreen },
    lightText: { color: colours.lightGreen },
    lighterText: { color: colours.offWhite },
    //button styles
    button: { backgroundColor: colours.accentBrown, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 6, alignItems: "center", },
    buttonText: { color: colours.lightGreen, fontSize: 16, fontWeight: "bold", fontFamily: 'InclusiveSans_700Bold' },
    submitButton: { backgroundColor: colours.mediumGreen, padding: 10, borderRadius: 5, width: '50%', },
    submitButtonText: { color: colours.offWhite, fontWeight: "bold", textAlign: "center", fontFamily: 'InclusiveSans_700Bold' },
    logoutButton: { backgroundColor: colours.accentRed, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 6, alignItems: "center", marginTop: 20, width: '75%', marginLeft: 'auto', marginRight: 'auto', },
    logoutButtonText: { color: colours.offWhite, fontSize: 16, fontWeight: "bold", fontFamily: 'InclusiveSans_700Bold' },
    //page/view styles
    image: { flex: 1, width: '100%', height: '100%', },
    card: { width: '100%', backgroundColor: colours.darkGreen, borderRadius: 8, padding: 16, marginBottom: 16 },
    container: { flex: 1, backgroundColor: 'transparent', alignItems: 'center', justifyContent: 'center', padding: 20, },
    containerNoPadding: { flex: 1, backgroundColor: 'transparent', alignItems: 'center', justifyContent: 'center', },
    backgroundDark: { backgroundColor: colours.darkOverlay },
    backgroundDarker: { backgroundColor: colours.darkerOverlay },
    backgroundLight: { backgroundColor: colours.lightOverlay },
    scrollViewContainer: { flexGrow: 1, },
    viewContainer: { flex: 1, padding: 16, justifyContent: 'space-between', },
    backgroundScrollContainer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0, },
    backgroundWide: { width: '160%', height: '100%', resizeMode: 'cover', alignSelf: 'flex-start',},
    backgroundContent: { alignItems: 'flex-start' },
    overlayContent: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'flex-start', zIndex: 1, paddingTop: 20, backgroundColor: 'transparent', position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, },
    //login screen and registration screen styles
    input: { width: "90%", padding: 10, borderWidth: 2, borderRadius: 5, marginBottom: 10, borderColor: colours.mediumGreen, color: colours.darkGreen, backgroundColor: colours.offWhite, fontFamily: 'InclusiveSans_400Regular' },
    link: { color: colours.mediumGreen, marginTop: 10, fontFamily: 'InclusiveSans_400Regular' },
    //environment selection styles
    environmentButtons: { flexDirection: "row", justifyContent: "space-around", marginTop: 25, width: "100%", },
    environmentButton: { backgroundColor: withAlpha(colours.darkGreen, 0.75), width: 50, height: 50, paddingVertical: 15, paddingHorizontal: 15, borderRadius: 25, },
    selectedEnvironmentButton: { backgroundColor: withAlpha(colours.mediumGreen, 0.85), },
    environmentButtonText: { color: colours.offWhite, fontWeight: "bold", fontFamily: 'InclusiveSans_700Bold', textAlign: 'center', },
    //bird styles (temporary dimensions)
    birdAbsolute: { position: 'absolute', transform: [{ translateX: -60 }, { translateY: -60 }], zIndex: 2 }, 
    birdImage: { width: 120, height: 120, resizeMode: 'contain', justifyContent: 'center', alignItems: 'center', },
    //game question styles
    questionAnswerContainer: { flex: 1, width: '100%', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, zIndex: 2, },
    questionContainer: { marginTop: 16, padding: 16, backgroundColor: withAlpha(colours.darkGreen, 0.8), borderRadius: 16, width: '90%', alignSelf: 'center', },
    answerContainer: { marginBottom: 24, padding: 16, backgroundColor: withAlpha(colours.darkGreen, 0.8), borderRadius: 16, width: '90%', alignSelf: 'center', },
    questionText: { fontSize: 18, color: colours.offWhite, marginBottom: 6, textAlign: 'center', fontFamily: 'InclusiveSans_400Regular' },
    answerButton: { backgroundColor: withAlpha(colours.mediumGreen, 0.9), paddingVertical: 10, paddingHorizontal: 16, borderRadius: 12, marginVertical: 6, width: '100%', alignItems: 'center', },
    answerButtonText: { color: colours.offWhite, fontSize: 16, textAlign: 'center', fontFamily: 'InclusiveSans_400Regular' },
    correctAnswerButton: { backgroundColor: withAlpha(colours.accentYellow, 0.9), },
    incorrectAnswerButton: { backgroundColor: withAlpha(colours.accentRed, 0.9), },
    //achievement styles
    achievementItem: { flexDirection: 'column', backgroundColor: withAlpha(colours.darkGreen, 0.8), borderRadius: 10, padding: 12, marginBottom: 12, width: '100%', },
    achievementTopRow: { flexDirection: 'row', alignItems: 'center', width: '100%' },
    achievementBadge: { width: 60, height: 60, justifyContent: 'center', alignItems: 'center', marginRight: 12, },
    achievementTextContainer: { flex: 1, justifyContent: 'center', },
    achievementTitle: { fontSize: 18, fontWeight: 'bold', color: colours.lightGreen, marginBottom: 4, fontFamily: 'InclusiveSans_700Bold' },
    achievementDescription: { fontSize: 14, color: colours.offWhite, marginBottom: 8, fontFamily: 'InclusiveSans_400Regular' },
    achievementStatsRow: { flexDirection: 'column', justifyContent: 'space-between', marginTop: 8, width: '100%', },
    achievementDate: { fontSize: 12, color: colours.lightGreen, fontFamily: 'InclusiveSans_400Regular' },
    achievementPercent: { fontSize: 12, color: colours.lightGreen, fontFamily: 'InclusiveSans_400Regular' },
    //logbook styles
    logbookTitle: { fontSize: 32, marginTop: 20, marginBottom: 20, textAlign: 'center', fontFamily: 'FuzzyBubbles_700Bold' },
    logbookSubtitle: { fontSize: 24, textAlign: 'center', fontFamily: 'FuzzyBubbles_400Regular' },
    logbookBirdGrid: { flexDirection: 'column', flexWrap: 'wrap', justifyContent: 'center', marginTop: 12, },
    logbookBirdCard: { width: '100%', height: 45, margin: 8, alignItems: 'left', flexDirection: 'row', gap: 16, },
    logbookBirdImage: { width: 40, height: 40, borderRadius: 8, },
    logbookBirdName: { marginTop: 8, fontSize: 24, color: colours.darkGreen, textAlign: 'center', fontFamily: 'FuzzyBubbles_400Regular' },
    logbookPageControls: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, paddingHorizontal: 32, },
    logbookPageButton: { padding: 8, },
    logbookPageButtonText: { fontSize: 18, color: colours.darkGreen, fontWeight: 'bold', fontFamily: 'FuzzyBubbles_700Bold' },
    //modal styles
    modalOverlay: { flex: 1, backgroundColor: colours.darkOverlay, justifyContent: 'center', alignItems: 'center', padding: 16, },
    modalContent: { backgroundColor: colours.dullGreen, borderRadius: 10, padding: 16, width: '100%', maxWidth: 400, },
    modalTop: { flexDirection: 'row', marginBottom: 16, gap: 16, },
    modalImage: { width: 100, height: 100, borderRadius: 8, resizeMode: 'contain', },
    modalTitle: { fontSize: 24, color: colours.offWhite, marginTop: 20, marginBottom: 4, fontFamily: 'FuzzyBubbles_700Bold' },
    modalSubtitle: { fontSize: 16, color: colours.lightGreen, marginBottom: 12, fontFamily: 'FuzzyBubbles_400Regular' },
    modalDetails: { marginTop: 8, },
    detailRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8, },
    detailLabel: { fontSize: 16, color: colours.lightGreen, marginBottom: 12, fontFamily: 'FuzzyBubbles_700Bold', width: 120, flexShrink: 0 },
    detailValue: { fontSize: 16, color: colours.offWhite, marginBottom: 12, fontFamily: 'FuzzyBubbles_400Regular', flex: 1, flexWrap: 'wrap', textAlign: 'right' },
    modalActions: { alignItems: 'flex-end', },
    closeButton: { backgroundColor: colours.accentRed, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 6, alignItems: "center", },
    closeButtonText: { color: colours.offWhite, fontSize: 16, fontFamily: 'FuzzyBubbles_700Bold' },
    modalButtons: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, marginTop: 16, },
    //gallery styles
    galleryButton: { backgroundColor: colours.mediumGreen, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 6, alignItems: "center", },
    galleryButtonText: { color: colours.offWhite, fontSize: 16, fontFamily: 'FuzzyBubbles_700Bold' },
    galleryGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', },
    galleryThumb: { flex: 1, maxWidth: '48%', aspectRatio: 1, borderRadius: 8, backgroundColor: '#000', margin: 6, overflow: 'hidden' },
    galleryThumbImage: { width: '100%', height: '100%', backgroundColor: 'transparent', },
    //about game styles
    paragraph: { fontSize: 16, marginBottom: 12, lineHeight: 22, fontFamily: 'InclusiveSans_400Regular', textAlign: 'center' },
    creditsContainer: { marginTop: 40, marginBottom: 40, borderTopWidth: 1, borderTopColor: withAlpha(colours.offWhite, 0.3), paddingTop: 20, },
    creditsTitle: { fontSize: 28, fontWeight: 'bold', marginBottom: 16, textAlign: 'center', fontFamily: 'InclusiveSans_700Bold' },
    creditsText: { fontSize: 16, marginBottom: 8, textAlign: 'center', fontFamily: 'InclusiveSans_400Regular' },
});