import { StyleSheet } from 'react-native';
import { colours, withAlpha } from './colourScheme';

export const styles = StyleSheet.create({
    topMargin: { marginTop: 50 },
    mb4: { marginBottom: 16 },
    row: { flexDirection: "row", justifyContent: "center", alignItems: "center", marginVertical: 8, },
    //text styles
    rowCenter: { alignItems: 'center', justifyContent: 'center' },
    title: { fontSize: 32, fontWeight: 'bold', marginBottom: 24, textAlign: 'center' },
    subtitle: { fontSize: 24, marginBottom: 16, textAlign: 'center' },
    heading: { fontWeight: 'bold' },
    sectionTitle: { fontWeight: 'bold', marginBottom: 8 },
    bold: { fontWeight: 'bold' },
    darkText: { color: colours.darkGreen },
    lightText: { color: colours.lightGreen },
    lighterText: { color: colours.offWhite },
    //button styles
    button: { backgroundColor: colours.accentBrown, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 6, alignItems: "center", },
    buttonText: { color: colours.lightGreen, fontSize: 16, fontWeight: "bold", },
    submitButton: { backgroundColor: colours.mediumGreen, padding: 10, borderRadius: 5, width: '50%', },
    submitButtonText: { color: colours.offWhite, fontWeight: "bold", textAlign: "center", },
    logoutButton: { backgroundColor: colours.accentRed, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 6, alignItems: "center", marginTop: 20, width: '75%', marginLeft: 'auto', marginRight: 'auto', },
    logoutButtonText: { color: colours.offWhite, fontSize: 16, fontWeight: "bold", },
    //page/view styles
    image: { flex: 1, width: '100%', height: '100%', },
    card: { width: '100%', backgroundColor: colours.darkGreen, borderRadius: 8, padding: 16, marginBottom: 16 },
    container: { flex: 1, backgroundColor: 'transparent', alignItems: 'center', justifyContent: 'center', padding: 20, },
    containerNoPadding: { flex: 1, backgroundColor: 'transparent', alignItems: 'center', justifyContent: 'center', },
    backgroundDark: { backgroundColor: colours.darkOverlay },
    backgroundLight: { backgroundColor: colours.lightOverlay },
    scrollViewContainer: { flexGrow: 1, },
    viewContainer: { flex: 1, padding: 16, justifyContent: 'space-between', },
    backgroundScrollContainer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0, },
    backgroundWide: { width: '160%', height: '100%', resizeMode: 'cover', alignSelf: 'flex-start',},
    backgroundContent: { alignItems: 'flex-start' },
    overlayContent: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'flex-start', zIndex: 1, paddingTop: 20, backgroundColor: 'transparent', position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, },
    //login screen and registration screen styles
    input: { width: "90%", padding: 10, borderWidth: 2, borderRadius: 5, marginBottom: 10, borderColor: colours.mediumGreen, color: colours.darkGreen, backgroundColor: colours.offWhite, },
    link: { color: colours.mediumGreen, marginTop: 10 },
    //environment selection styles
    environmentButtons: { flexDirection: "row", justifyContent: "space-around", marginTop: 25, width: "100%", },
    environmentButton: { backgroundColor: withAlpha(colours.darkGreen, 0.75), width: 50, height: 50, paddingVertical: 15, paddingHorizontal: 15, borderRadius: 25, },
    selectedEnvironmentButton: { backgroundColor: withAlpha(colours.mediumGreen, 0.85), },
    environmentButtonText: { color: colours.offWhite, fontWeight: "bold", },
    //bird styles (temporary dimensions)
    birdAbsolute: { position: 'absolute', transform: [{ translateX: -60 }, { translateY: -60 }], zIndex: 2 }, 
    birdImage: { width: 120, height: 120, resizeMode: 'contain', justifyContent: 'center', alignItems: 'center', },
    //game question styles
    questionAnswerContainer: { flex: 1, width: '100%', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, zIndex: 2, },
    questionContainer: { marginTop: 16, padding: 16, backgroundColor: withAlpha(colours.darkGreen, 0.8), borderRadius: 16, width: '90%', alignSelf: 'center', },
    answerContainer: { marginBottom: 24, padding: 16, backgroundColor: withAlpha(colours.darkGreen, 0.8), borderRadius: 16, width: '90%', alignSelf: 'center', },
    questionText: { fontSize: 18, color: colours.offWhite, marginBottom: 6, textAlign: 'center', },
    answerButton: { backgroundColor: withAlpha(colours.mediumGreen, 0.9), paddingVertical: 10, paddingHorizontal: 16, borderRadius: 12, marginVertical: 6, width: '100%', alignItems: 'center', },
    answerButtonText: { color: colours.offWhite, fontSize: 16, textAlign: 'center', },
    correctAnswerButton: { backgroundColor: withAlpha(colours.accentYellow, 0.9), },
    incorrectAnswerButton: { backgroundColor: withAlpha(colours.accentRed, 0.9), },
    //achievement styles
    achievementItem: { flexDirection: 'column', backgroundColor: withAlpha(colours.darkGreen, 0.8), borderRadius: 10, padding: 12, marginBottom: 12, width: '100%', },
    achievementTopRow: { flexDirection: 'row', alignItems: 'center', width: '100%' },
    achievementBadge: { width: 60, height: 60, justifyContent: 'center', alignItems: 'center', marginRight: 12, },
    achievementTextContainer: { flex: 1, justifyContent: 'center', },
    achievementTitle: { fontSize: 18, fontWeight: 'bold', color: colours.lightGreen, marginBottom: 4, },
    achievementDescription: { fontSize: 14, color: colours.offWhite, marginBottom: 8, },
    achievementStatsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8, width: '100%', },
    achievementDate: { fontSize: 12, color: colours.lightGreen, },
    achievementPercent: { fontSize: 12, color: colours.lightGreen, },
    //logbook styles
    logbookBirdGrid: { flexDirection: 'column', flexWrap: 'wrap', justifyContent: 'center', marginTop: 12, },
    logbookBirdCard: { width: '100%', height: 45, margin: 8, alignItems: 'left', flexDirection: 'row', gap: 16, },
    logbookBirdImage: { width: 40, height: 40, borderRadius: 8, },
    logbookBirdName: { marginTop: 8, fontSize: 16, color: colours.darkGreen, textAlign: 'center', },
    logbookPageControls: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, paddingHorizontal: 32, },
    logbookPageButton: { padding: 8, },
    logbookPageButtonText: { fontSize: 18, color: colours.darkGreen, fontWeight: 'bold', },
    //modal styles
    modalOverlay: { flex: 1, backgroundColor: withAlpha(colours.darkOverlay, 0.9), justifyContent: 'center', alignItems: 'center', padding: 16, },
    modalContent: { backgroundColor: colours.offWhite, borderRadius: 10, padding: 16, width: '100%', maxWidth: 400, },
    modalTop: { flexDirection: 'row', marginBottom: 16, },
    modalImage: { width: 100, height: 100, borderRadius: 8, },
});